sudo: required
dist: trusty

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

language: node_js
node_js:
  - "lts/*"

install:
  - npm install

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - "node_modules"

script:
  - ng build --prod --aot
  - ng test

notifications:
  email:
    recipients:
      - nielhekkens@neo-endurance.com
    on_success: always # default: change
    on_failure: always # default: always