sudo: required
dist: trusty

addons:
  chrome: stable

before_install:
  - google-chrome-stable --no-sandbox

language: node_js
node_js:
  - "lts/*"

before_install:


install:
  - npm install

cache:
  directories:
    - "node_modules"