sudo: required
dist: trusty

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

language: node_js
node_js:
  - "lts/*"

install:
  - npm install

cache:
  directories:
    - "node_modules"